create table "public"."mailingList" (
    "id" bigint generated by default as identity not null,
    "email" text not null default ''::text
);


alter table "public"."mailingList" enable row level security;

CREATE UNIQUE INDEX "mailingList_pkey" ON public."mailingList" USING btree (id);

alter table "public"."mailingList" add constraint "mailingList_pkey" PRIMARY KEY using index "mailingList_pkey";

grant delete on table "public"."mailingList" to "anon";

grant insert on table "public"."mailingList" to "anon";

grant references on table "public"."mailingList" to "anon";

grant select on table "public"."mailingList" to "anon";

grant trigger on table "public"."mailingList" to "anon";

grant truncate on table "public"."mailingList" to "anon";

grant update on table "public"."mailingList" to "anon";

grant delete on table "public"."mailingList" to "authenticated";

grant insert on table "public"."mailingList" to "authenticated";

grant references on table "public"."mailingList" to "authenticated";

grant select on table "public"."mailingList" to "authenticated";

grant trigger on table "public"."mailingList" to "authenticated";

grant truncate on table "public"."mailingList" to "authenticated";

grant update on table "public"."mailingList" to "authenticated";

grant delete on table "public"."mailingList" to "service_role";

grant insert on table "public"."mailingList" to "service_role";

grant references on table "public"."mailingList" to "service_role";

grant select on table "public"."mailingList" to "service_role";

grant trigger on table "public"."mailingList" to "service_role";

grant truncate on table "public"."mailingList" to "service_role";

grant update on table "public"."mailingList" to "service_role";


